// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiMRCG.Contexts;

namespace WebApiMRCG.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApiMRCG.Entities.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<double>("Preco");

                    b.HasKey("AnimalId");

                    b.ToTable("Animal");
                });

            modelBuilder.Entity("WebApiMRCG.Entities.CompraGado", b =>
                {
                    b.Property<int>("CompraGadoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataEntrega");

                    b.Property<int>("PecuaristaId");

                    b.HasKey("CompraGadoId");

                    b.HasIndex("PecuaristaId");

                    b.ToTable("CompraGado");
                });

            modelBuilder.Entity("WebApiMRCG.Entities.CompraGadoItem", b =>
                {
                    b.Property<int>("CompraGadoItemId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnimalId");

                    b.Property<int>("CompraGadoId");

                    b.Property<int>("Quantidade");

                    b.HasKey("CompraGadoItemId");

                    b.HasIndex("AnimalId");

                    b.HasIndex("CompraGadoId");

                    b.ToTable("CompraGadoItem");
                });

            modelBuilder.Entity("WebApiMRCG.Entities.Pecuarista", b =>
                {
                    b.Property<int>("PecuaristaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("PecuaristaId");

                    b.ToTable("Pecuarista");
                });

            modelBuilder.Entity("WebApiMRCG.Entities.CompraGado", b =>
                {
                    b.HasOne("WebApiMRCG.Entities.Pecuarista", "Pecuarista")
                        .WithMany("CompraGados")
                        .HasForeignKey("PecuaristaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApiMRCG.Entities.CompraGadoItem", b =>
                {
                    b.HasOne("WebApiMRCG.Entities.Animal", "Animal")
                        .WithMany("CompraGadoItens")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApiMRCG.Entities.CompraGado", "CompraGado")
                        .WithMany("CompraGadoItens")
                        .HasForeignKey("CompraGadoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
